# autostart.conf

$polkit = /usr/libexec/kf6/polkit-kde-authentication-agent-1
#$kwalletInit = exec --no-startup-id /usr/lib/pam_kwallet_init

# menu bar
exec-once = /usr/bin/waybar

# hyprpaper
# exec-once = hyprpaper

## services
# polkit
exec-once = $polkit

# notification system
exec-once = /usr/bin/swaync

# unlock kwallet
# exec-once = /usr/share/hyprland/scripts/load-kwallet.sh

# load kwallet dependent apps
# exec-once = /usr/share/hyprland/scripts/load-kwallet-apps.sh

# dbus stuff
exec-once = /usr/bin/dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# nextcloud
# exec-once = sleep 1 && flatpak run --branch=stable --arch=x86_64 --command=nextcloud --file-forwarding com.nextcloud.desktopclient.nextcloud

# exec-once = akregator --hide-mainwindow
