# discord_workspace.conf

$discord_class = class:^(vesktop)$|^(discord)$|^(com.discord.app.Discord)$|^(WebCord)$|^(equibop)$

# workspace
workspace = special:discord

# window rule
windowrule = workspace special:discord silent, $discord_class
#windowrule = workspace special:discord silent, class:^(discord)$
#windowrule = opacity 0.9 0.9, $discord_class
windowrule = allowsinput on, $discord_class

# key binds
$mainMod = SUPER
#bind = $mainMod, D, focuswindow, vesktop
bind = $mainMod, D, togglespecialworkspace, discord
bind = $mainMod SHIFT, D, movetoworkspace, special:discord

# discord overlay
#exec-once = discover-overlay