# game_workspace.conf

# workspace number
$game-workspace-number = 5

exec-once = uwsm app -- steam.desktop

# window rules
windowrule = workspace 9 silent, title:^(Steam)$

# key binds
$mainMod = SUPER
bind = $mainMod, G, focuswindow, class:^(gamescope|steam)

# To put the window rules for the game workspace

# steam apps
windowrule = workspace $game-workspace-number silent, class:^steam_app_\d+$

# gamescope
windowrule = fullscreen, class:^(gamescope)$
windowrule = workspace $game-workspace-number silent, class:^(gamescope)$

# Minecraft
windowrule = workspace $game-workspace-number, class:^Minecraft.*

# factorio
windowrule = workspace $game-workspace-number, class:^(factorio)$

# RetroArch flatpak
windowrule = workspace $game-workspace-number, class:^(org.libretro.RetroArch)$

# dolphin emulator
windowrule = workspace $game-workspace-number, class:^(dolphin-emu)$

# Slay the Spire
windowrule = workspace $game-workspace-number, class:^(Slay the Spire)$

# Terraria
windowrule = workspace $game-workspace-number, class:^(dotnet)$
windowrule = fullscreen, class:^(dotnet)$
