# terminal.conf
$terminal = uwsm app -- kitty.desktop

# workspace
workspace = special:terminal

# launch a terminal
exec-once = [workspace special:terminal silent] $terminal

# key binds
$mainMod = SUPER
bind = $mainMod, T, togglespecialworkspace, terminal
bind = $mainMod SHIFT, T, movetoworkspace, special:terminal
