# terminal.conf

# workspace
workspace = special:terminal

# key binds
$mainMod = SUPER
bind = $mainMod, T, togglespecialworkspace, terminal
bind = $mainMod SHIFT, T, movetoworkspace, special:terminal
