#!/usr/bin/env bash

HYPRCMDS=$(hyprctl -j clients | jq -j '.[] | "dispatch closewindow address:\(.address); "')
hyprctl --batch "$HYPRCMDS" >>/tmp/hyprexitwithgrace.log 2>&1

notify-send "power controls" "Closing Applications..."

sleep 2

COUNT=$(hyprctl clients | grep "class:" | wc -l)

if [ "$COUNT" -eq "0" ]; then
  notify-send "power controls" "Closed Applications."
  return
else
  notify-send "power controls" "Some apps didn't close. Not shutting down."
  exit 1
fi
