# media_binds.conf
$mainMod = SUPER

# media play-pause toggle
bind = , XF86AudioPlay, exec, playerctl play-pause

# media volume up/down
bind = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%-
bind = , XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 1%+

# media volume up/down
bind = $mainMod, XF86AudioLowerVolume, exec, playerctl position 5-
bind = $mainMod, XF86AudioRaiseVolume, exec, playerctl position 5+

# media pause
bind = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
